name: Dart

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: dart pub get

      - name: Check if code is formatted
        run: dartfmt --dry-run --set-exit-if-changed .

      - name: Run analyzer
        run: dart analyze --fatal-infos

      - uses: southpolesteve/cosmos-emulator-github-action@v1
      - name: Run tests
        run: dart test -r expanded